name: Create Archive
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
- name: Upload Release
  uses: ncipollo/release-action@v1
  with:
    artifacts: "release.zip"
    token: ${{ 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 }}
        filename: 'release.zip'
        exclusions: '*.git* README.md'
